### ISSUE TITLE
Visual bug with vim panel

### ISSUE THREAD

**Issue by chrisgrieser** [cumany/obsidian-floating-toc-plugin#1]
Thanks so much for reviving this plugin. Haven't noticed it before, it's a real hidden gem.

I noticed a minor visual issue, when floating toc is activated, it push the whole editor to the right. This creates the gap here with the vim panel (only visible when using `/` or `:` in vim mode).

![image](https://user-images.githubusercontent.com/73286100/190933742-227cb045-f9e0-49c0-a909-7aaf753d9b82.png)

This css-snippet here fixes the issue, however, I don't know whether this is a good solution, since it kinda only treats the symptom instead of the cause (therefore not making a PR.)
```css
.floating-toc-div + .markdown-source-view .cm-panels {
	position: absolute;
}
```
