### ISSUE TITLE
[样式问题] 阅读/编辑模式左边距不一致（pin状态下）

### ISSUE THREAD

**Issue by Azona77** [cumany/obsidian-floating-toc-plugin#105]
- 中文论坛有用户反映：pin状态下，编辑模式正常，阅读模式页面左边距缺失，**挡住了正文内容**
- 效果如图：
  - ![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/76045875/e239a834-3683-4415-919d-0d793ad9fad8)

- 使用css脚本可将阅读模式正文边距对齐到编辑模式：
 ```css
.floating-toc-div.floating-left.pin ~ .markdown-reading-view > .markdown-preview-view.markdown-rendered{
  padding-left: var(--floating-toc-line-width)!important;
}
```

- 编辑和阅读模式元素排布不太一样，不清楚这样加上边距会不会不规范？或许可以加一个开关？
