### ISSUE TITLE
能否直接显示标签在“文字”前面呢？

### ISSUE THREAD

**Issue by llity** [cumany/obsidian-floating-toc-plugin#12]
如图，类似bear哪种。
<img width="398" alt="image" src="https://user-images.githubusercontent.com/11771112/191936756-01e3e573-4dcf-4fdf-9e0d-c7f56dc9780e.png">

**Comment by cumany** [comment]
用下面的css片段即可实现
```css
li.heading-list-item .text::after
{
  float: left;
}
```
