### ISSUE TITLE
CSS code to render H1 headings as capitals

### ISSUE THREAD

**Issue by DutchPete** [cumany/obsidian-floating-toc-plugin#25]
For the H1 headings in the main text I use:

```css
/* Automatically convert H1 headings to capitals in text */
.cm-header-1, .markdown-preview-view h1 {
    text-transform: uppercase;
}
```

Is it possible to get the same in the floating toc?

**Comment by cumany** [comment]
Of course it can be done. But for now you can consider using css snippets to implement
```css
.heading-list-item[data-level="1"] .text{
  text-transform: uppercase;
}
 
```
