### ISSUE TITLE
样式自己修改了一下，看有没有参考价值！

### ISSUE THREAD

**Issue by Peingxious** [cumany/obsidian-floating-toc-plugin#59]
![动画](https://github.com/cumany/obsidian-floating-toc-plugin/assets/79826986/efb5112d-09f3-4cc5-97e4-82cfbe2472c2)

```css

.floating-toc {
    top: 15%;
}

.floating-toc-div .toolbar {
    top: calc(15% - 25px);
}
div.text-wrap > a > img{
    display:none;
    _max-height:30px;
}

div.text-wrap > a{
  ——color:red !important;
  ——background-color: #00142B!important;
}

ul.floating-toc div.text-wrap > a{
background-color:red;
padding:2px 8px !important;
}

ul.floating-toc {
--background-color:red;
margin-top:0px !important;
margin-bottom:0px !important;
}

.heading-list-item.located .text::before {
    content: "👁️";
    margin-right: 2px;
}

.heading-list-item.located .text {
    border:solid 1px ;
    background-color: rgba(var(--floating-toc-highlight-color-rgb),0.1);
}
.heading-list-item.located .text {
    font-weight: border;
}

.heading-list-item.focus .text-wrap .text {
    font-weight: normal;
}
.heading-list-item.focus .text::before {
    content: "️";
    margin-right: 2px;
}

.heading-list-item .text-wrap.located .text {
    background-color: var(--floating-toc-header-background-color);
}
   
.floating-toc-div.pin .floating-toc, .floating-toc:hover {
    z-index: 10;
 max-width: 70%;
}

.heading-list-item.located .text-wrap:not(.located) .text ,
body.enable-heading-nowrap .heading-list-item .text-wrap .text{
    max-width: 10em;
}
```
