### ISSUE TITLE
Latest update adds delay when hovering the floating ToC

### ISSUE THREAD

**Issue by chrisgrieser** [cumany/obsidian-floating-toc-plugin#7]
Hi, it seems the latest update introduced some sort of small delay. Previously, when I hovered the floating ToC, the outline showed up instantly. With the latest update, it takes a second before they are displayed?

**Comment by cumany** [comment]
Yes This is due to the addition of the css delay animation. The reason for doing this is that sometimes the mouse moves past the toc and the toc triggers and pops up easily. So now the logic is to hover for 0.5 seconds before popping up so that it pops up when it's really needed.

**Comment by chrisgrieser** [comment]
> The reason for doing this is that sometimes the mouse moves past the toc and the toc triggers and pops up easily. So now the logic is to hover for 0.5 seconds before popping up so that it pops up when it's really needed.

yes, that makes absolutely sense, but I think 0.5 seconds is a bit much. I, too, have added a small delay to some hover effects in my theme, and I feel like 0.2 seconds is the right amount of delay for that – high enough to prevent accidental triggering, but low enough to not make you wait.

But I also see that this is a bit of a personal choice. Could you maybe add an option to adjust the amount of delay?

> Yes This is due to the addition of the css delay animation.

Is that hard-coded in the plugin somewhere? Cause I can't find a 500ms delay in the plugin's [style.css](https://github.com/cumany/obsidian-floating-toc-plugin/blob/master/styles.css). (in which case I would have simply lowered the delay myself with a CSS snippet.)

**Comment by cumany** [comment]
Yes, you can use the following css snippet to change the delay time you need
```css
.floating-toc:hover .heading-list-item>.text-wrap {
transition-delay:0.5s;
transition-property:opacity;
transition-timing-function: ease-in-out;
-webkit-transition-delay:0.5s;
-webkit-transition-property: opacity;
-webkit-transition-timing-function: ease-in-out;
}

```

**Comment by chrisgrieser** [comment]
I tried the snippet, set the delays to 0, but it has no effect, there is still a delay.

looking at the dev tools, it seems the values are somehow invalid: 
<img width="743" alt="Pasted image 2022-09-23 16 51 18" src="https://user-images.githubusercontent.com/73286100/191989469-f61ecc31-6c56-4eec-b2d7-bb1c9c66dcc1.png">

**Comment by cumany** [comment]
> I tried the snippet, set the delays to 0, but it has no effect, there is still a delay.
> 
> looking at the dev tools, it seems the values are somehow invalid: <img alt="Pasted image 2022-09-23 16 51 18" width="743" src="https://user-images.githubusercontent.com/73286100/191989469-f61ecc31-6c56-4eec-b2d7-bb1c9c66dcc1.png">

This issue is related to css priority, it seems that the snippet priority is not high enough, try this
```css
ul.floating-toc:hover .heading-list-item>.text-wrap {
  transition-delay:0s;
  -webkit-transition-delay:0s;
  }
```
